language: go
sudo: false

go:
  - tip

install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

script:
  - $HOME/gopath/bin/goveralls -repotoken 95VMUB5RHe9nYKgiMEtuwvIZJOPD20nmk
