language: go
sudo: false

go:
  - 1.5
  - tip

install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

script:
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken 95VMUB5RHe9nYKgiMEtuwvIZJOPD20nmk
